### ISSUE TITLE
Feature request: Allow to specify the server IP for wiki domain resolution

### ISSUE THREAD

**Issue by yusancky** [fastily/pwiki#2]
I am using this library in my automation project. I would like to request a feature that allows users to specify the server IP address for wiki domain resolution. This feature would be similar to modifying the `Hosts` file, enabling users to override the default DNS lookup and resolve wiki domains to specific IP addresses.

This functionality would be particularly useful in scenarios where network configurations or security policies restrict access to certain domains, or when testing against specific wiki instances that are not publicly accessible. By providing the ability to specify the server IP address, users can ensure that the library connects to the intended wiki instance without relying on external DNS resolution.

Thank you for considering my request.

**Comment by fastily** [comment]
Hi, this seems out of scope for pwiki.  If you need to override default DNS lookups, why not just modify your Hosts file?  Or better, why not run your application in a docker container (which supports the functionality you're requesting out of the box)?

**Comment by fastily** [comment]
closing as out of scope per my comment above
